name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

permissions:
  contents: read

jobs:
  print-chrome-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print Chrome version
        run: /usr/bin/google-chrome --version

